export const clerkAppearance = {
  variables: {
    colorBackground: 'transparent',
    colorInputBackground: '#0A0A0E',
    colorText: '#F5F1EB',
    colorTextSecondary: '#8A8A92',
    colorTextOnPrimaryBackground: '#0A0A0E',
    colorPrimary: '#2CB87A',
    colorDanger: '#EF4444',
    colorSuccess: '#4FD69B',
    colorNeutral: '#F5F1EB',
    colorInputText: '#F5F1EB',
    borderRadius: '0.625rem',
    fontFamily: 'ui-sans-serif, system-ui, sans-serif',
    fontWeight: { normal: 400, medium: 500, bold: 700 },
    spacingUnit: '1rem',
  },
  elements: {
    rootBox: 'w-full',
    card: '!bg-transparent !shadow-none !border-0 p-0 w-full',
    headerTitle: 'hidden',
    headerSubtitle: 'hidden',
    socialButtonsBlockButton: '!bg-(--surface-elevated) !border !border-(--border) !text-(--foreground) hover:!bg-(--border) transition-colors rounded-full',
    socialButtonsBlockButtonText: '!text-(--foreground) font-medium',
    dividerLine: '!bg-(--border)',
    dividerText: '!text-(--muted)',
    formFieldLabel: '!text-(--muted) text-xs font-medium uppercase tracking-wide',
    formFieldInput: '!bg-(--surface) !border-(--border) !text-(--foreground) placeholder:!text-(--muted) focus:!border-(--accent) rounded-lg',
    formButtonPrimary: '!bg-(--accent) hover:!bg-(--accent-strong) !text-(--background) font-semibold rounded-full transition-colors',
    footerActionText: '!text-(--muted)',
    footerActionLink: '!text-(--accent) hover:!text-(--accent-strong) font-medium',
    identityPreviewText: '!text-(--foreground)',
    identityPreviewEditButton: '!text-(--accent)',
    formFieldErrorText: '!text-red-400 text-xs',
    alertText: '!text-(--foreground)/80',
    badge: '!bg-(--accent-muted) !text-(--accent)',
  },
}
