export const clerkAppearance = {
  variables: {
    colorBackground: '#0A0F0D',
    colorInputBackground: '#020202',
    colorText: '#ffffff',
    colorTextSecondary: 'rgba(255,255,255,0.55)',
    colorTextOnPrimaryBackground: '#ffffff',
    colorPrimary: '#0A9548',
    colorDanger: '#16DB65',
    colorSuccess: '#16DB65',
    colorNeutral: '#ffffff',
    colorInputText: '#ffffff',
    borderRadius: '0.75rem',
    fontFamily: 'Inter, sans-serif',
    fontWeight: { normal: 400, medium: 500, bold: 700 },
    spacingUnit: '1rem',
  },
  elements: {
    card: 'bg-[#0A0F0D] border border-white/10 shadow-2xl',
    headerTitle: 'text-white font-bold',
    headerSubtitle: 'text-white/50',
    socialButtonsBlockButton: 'bg-white/5 border border-white/10 text-white hover:bg-white/10 transition-colors',
    socialButtonsBlockButtonText: 'text-white font-medium',
    dividerLine: 'bg-white/10',
    dividerText: 'text-white/30',
    formFieldLabel: 'text-white/60 text-xs font-medium uppercase tracking-wide',
    formFieldInput: 'bg-[#020202] border-white/10 text-white placeholder:text-white/20 focus:border-[#0A9548] rounded-lg',
    formButtonPrimary: 'bg-[#0A9548] hover:bg-[#0A9548]/90 text-white font-semibold rounded-lg transition-colors',
    footerActionText: 'text-white/50',
    footerActionLink: 'text-[#16DB65] hover:text-[#0A9548] font-medium',
    identityPreviewText: 'text-white',
    identityPreviewEditButton: 'text-[#16DB65]',
    formFieldErrorText: 'text-[#16DB65] text-xs',
    alertText: 'text-white/80',
    badge: 'bg-[#0A9548]/20 text-[#16DB65]',
  },
}
