export const clerkAppearance = {
  variables: {
    colorBackground: '#080808',
    colorInputBackground: '#0F0F0F',
    colorText: '#F2F2F2',
    colorTextSecondary: '#A0A0A0',
    colorTextOnPrimaryBackground: '#F2F2F2',
    colorPrimary: '#2CB87A',
    colorDanger: '#E5484D',
    colorSuccess: '#2CB87A',
    colorNeutral: '#F2F2F2',
    colorInputText: '#F2F2F2',
    borderRadius: '0.5rem',
    fontFamily: 'Geist, sans-serif',
    fontWeight: { normal: 400, medium: 500, bold: 600 },
    spacingUnit: '0.75rem',
  },
  elements: {
    card: 'bg-bg-surface border border-border-soft',
    headerTitle: 'text-text-primary font-semibold',
    headerSubtitle: 'text-text-secondary',
    socialButtonsBlockButton: 'bg-bg-subtle border border-border-soft text-text-primary hover:bg-bg-hover transition-colors',
    socialButtonsBlockButtonText: 'text-text-primary font-medium',
    dividerLine: 'bg-border-faint',
    dividerText: 'text-text-muted',
    formFieldLabel: 'text-text-muted text-xs font-medium uppercase tracking-wide',
    formFieldInput: 'bg-bg-subtle border border-border-soft text-text-primary placeholder:text-text-muted focus:border-border-strong focus:ring-1 focus:ring-border-strong rounded-md',
    formButtonPrimary: 'bg-accent hover:bg-accent-hover text-white font-medium rounded-md transition-colors',
    footerActionText: 'text-text-muted',
    footerActionLink: 'text-accent hover:text-accent-hover font-medium',
    identityPreviewText: 'text-text-primary',
    identityPreviewEditButton: 'text-accent',
    formFieldErrorText: 'text-error text-xs',
    alertText: 'text-text-secondary',
    badge: 'bg-accent-muted text-accent',
  },
}
