// PreToolUse (Edit|MultiEdit|Write): blocks secrets, lockfile and already-committed migrations.
import { readFileSync } from 'node:fs'
import { spawnSync } from 'node:child_process'

const input = JSON.parse(readFileSync(0, 'utf8') || '{}')
const file = String(input.tool_input?.file_path ?? '').replaceAll('\\', '/')
const name = file.split('/').pop() ?? ''

let reason = ''
if (/^\.env(\..+)?$/.test(name) && !name.endsWith('.example')) {
  reason = 'env files hold secrets and are never edited by Claude'
} else if (name === 'package-lock.json') {
  reason = 'package-lock.json is generated by npm'
} else if (/\/supabase\/migrations\/[^/]+\.sql$/.test(file)) {
  const tracked = spawnSync('git', ['ls-files', '--error-unmatch', file], { stdio: 'ignore' }).status === 0
  if (tracked) reason = 'committed migrations are immutable; add a new one with `supabase migration new`'
}

if (reason) {
  console.error(`Blocked edit of ${name}: ${reason}.`)
  process.exit(2)
}
